# .travis.yml

language: python
python:
  - "3.12"  # Puedes especificar la versión de Python que prefieras

# Instalar dependencias si las tienes
install:
  - pip install -r requirements.txt || true

# Ejecutar pruebas
script:
  - python -m unittest discover
